version: '2' 

services:
  web:
    build: web
    ports:
      - "4200:4200"

  api:
    build: api
    ports:
      - "3000:3000"
    links: 
        - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /srv/docker/mongodb:/var/lib/mongodb